//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicaciónMulticapas
{
    using System;
    using System.Collections.Generic;
    
    public partial class conexion1
    {
        public int id { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public Nullable<int> manzana { get; set; }
        public Nullable<int> edificio { get; set; }
        public string apartamento { get; set; }
    }
}
